on:
  push:
    branches:
      - master  





jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: "Login to Docker hub"
        run: docker login --username ${{ secrets.DOCKERHUP_USERNAME }} --password ${{ secrets.DOCKERHUP_TOCKEN }}
      
      - name: "Bulding docker image"
        run: docker build -t ${{ secrets.DOCKERHUP_USERNAME }}/myimage .

      - name: "pushing to Docker hub"
        run: docker push ${{ secrets.DOCKERHUP_USERNAME }}/myimage

      
        

    
    
